/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M19
 * Generated at: 2017-04-16 12:54:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import java.io.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>RF-iCare(尔福康)输液系统</title>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"width:100%; height: 200px;\">\r\n");
      out.write("  <div  align=\"center\" style=\"width: 30%; height: 100%; float:left\">\r\n");
      out.write("    <img src=\"images/logo.png\" style=\"max-width:100%; max-height: 100%\">\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div align=\"center\"  style=\"width: 70%; height: 50%; float:right\">\r\n");
      out.write("    <font size=\"5\">RF-iCare(尔福康)输液系统</font>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div align=\"center\"  style=\"width: 70%; height: 50%; float:right\">\r\n");
      out.write("    <p>请输入床号：</p>\r\n");
      out.write("    <form name=\"form1\" method=\"post\">\r\n");
      out.write("      <input type=\"text\" name=\"bed_num\" id=\"bed_num_id\">\r\n");
      out.write("      <input type=\"submit\" value=\"确定\">\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div style=\"clear:both\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");



	String filename = "RFiCare";
	String fileFolderName = "E:\\ReallyMySQL";
	int fileCount = 1;
	int step = 1;
	File fileFind = new File(fileFolderName);
	File[] fileArray = fileFind.listFiles();
	for (int i = 0; i < fileArray.length; i++) {
		if (fileArray[i].isFile() && fileArray[i].getName().startsWith(filename + "_")) {
			fileCount += step;
		}
	}
	
	
	String line = "";
	if(fileCount -2 > 0){
		fileCount -= 2;
	}else{
		line = "0,0,yes,0,0,NaCl";
	}

	File csv = new File(fileFolderName + "\\" + filename + "_" + fileCount + ".csv");

  BufferedReader br = null;
  try {
    br = new BufferedReader(new FileReader(csv));
  }catch (FileNotFoundException e){
    e.printStackTrace();
  }
  String everyLine = "";
  try {
    
    while ((line = br.readLine()) != null){
      everyLine = line;
      System.out.println(everyLine);
     
    }
    
  }catch (IOException e){
    e.printStackTrace();
  }



  String bed_num_input = request.getParameter("bed_num");
//  if (bed_num_input != null) {
//      response.sendRedirect("index.jsp?bed=" + bed_num_input);
//  }
//
//  String bed = request.getParameter("bed");

/*   String[] transfusionInfo = {
          //床号，剩余百分比，是否报警，每分钟滴数，剩余时间，药品信息
          "301,12.5,yes,50,15,生理盐水",
          "302,75.0,no,50,100,NaCl,",
          "303,12.5,yes,50,125,NaCl,",
          "304,12.5,yes,50,22,NaCl,",
          "305,75.0,no,50,30,NaCl,",
          "306,75.0,no,50,40,NaCl,",
          "307,75.0,no,50,4,NaCl,",
  }; */
  
  String transfusionInfo = "";
  transfusionInfo = everyLine;


  for (int i = 0; i < 1; i++){
	  System.out.println("#############"+transfusionInfo);
    String[] infoSplit = transfusionInfo.split(",");
    String bed_num = infoSplit[0];
    String liquid_left = infoSplit[1];
    String alert_flag = infoSplit[2];
    String speed = infoSplit[3];
    String time_left = infoSplit[4];
    String medcine_info = infoSplit[5];
    String name = infoSplit[6];
    String date = infoSplit[7];

    if (!bed_num.equals(bed_num_input)){
      continue;
    }

    out.println("<div style=\"width:100%; height:200px \">");
    out.println("<table border=\"0\" align=\"center\" width=\"100%\" height=\"100%\">");
    out.println("<tr>");

    if (liquid_left.equals("100.0")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_8.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("87.5")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_7.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("75.0")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_6.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("62.5")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_5.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("50.0")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_4.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("37.5")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_3.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("25.0")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_2.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("12.5")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_1.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }else if (liquid_left.equals("0.0")){
      out.println("<td width=\"50%\"><div align=\"center\"><img src=\"images/img/500_0.png\" style=\"max-width:100%; max-height: 100%\"></div></td>");
    }

    out.println("<td width=\"50%\">");
    out.println("<table border=\"0\" width=\"100%\" style=\"font-family:'宋体'; font-size:18px;\">\n");
    out.println("<tr><td>床&nbsp&nbsp号：" + bed_num + "</td></tr>");
    out.println("<tr><td>姓&nbsp&nbsp名：" + name + "</td></tr>");
    out.println("<tr><td>余&nbsp&nbsp量：" + liquid_left + "%" + "</td></tr>" );
    out.println("<tr><td>药&nbsp&nbsp品：" + medcine_info + "</td></tr>");
    out.println("<tr><td>日&nbsp&nbsp期：" + date + "</td></tr>");
    out.println("</table>");
    out.println("</td>");
    out.println("</tr>");
    out.println("</table>");
    out.println("</div>");
  }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
